language: generic

services: 
    - docker

before_install:
    - docker build -t omid29/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true omid29/docker-react npm run test

deploy: 
    provider: elastikbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-995863513652"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_acess_key:
        secure: "AWS_SECRET_KEY"